version: '3.8'

services:
  wallet-elements-test:
    image: ghcr.io/cryptogarageinc/elements-testing:v0.2.3
    volumes:
      - ./:/workspace/wallet-test
    working_dir: /workspace/wallet-test
    command: /bin/bash -c "/workspace/wallet-test/__tests__/docker-entrypoint.sh"

  wallet-bitcoin-test:
    image: ghcr.io/cryptogarageinc/elements-testing:v0.2.3
    volumes:
      - ./:/workspace/wallet-test
    working_dir: /workspace/wallet-test
    command: /bin/bash -c "/workspace/wallet-test/__tests__/docker-bitcoin-entrypoint.sh"

  wallet-update-package-lock:
    image: ghcr.io/cryptogarageinc/elements-testing:v0.2.3
    volumes:
      - ./:/workspace/wallet-test
    working_dir: /workspace/wallet-test
    command: /bin/bash -c "./tools/update_package.sh"
